version: 2
updates:
  - package-ecosystem: 'npm'
    directory: './'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: './packages/cli/templates/kita'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: './packages/cli/templates/kita-jsx'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    directory: './'
    schedule:
      interval: 'monthly'
