name: Code CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install --no-frozen-lockfile

      # Temporary fix until all code compiles :)
      - name: Build
        run: pnpm -r build

      # - name: Link kita binary
      #   run: pnpm i -g
      #   working-directory: packages/cli

      - name: Test
        run: pnpm test

      - name: Publish to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
